platform :ios, '15.4'
use_frameworks!

target 'iosApp' do
  pod 'data', :path => '../shared/core/data'
#   pod 'datastore', :path => '../shared/core/datastore'
#    pod 'model', :path => '../shared/core/model'

#   pod "SwiftUIRefresh"
  pod 'KMPNativeCoroutinesAsync', '~> 0.13.3' #:git => 'https://github.com/rickclephas/KMP-NativeCoroutines.git', :tag => '0.13.1'
  pod 'KMPNativeCoroutinesCombine', '~> 0.13.3' #:git => 'https://github.com/rickclephas/KMP-NativeCoroutines.git', :tag => '0.13.1'
end
