platform :ios, '15.0'
use_frameworks!

target 'iosApp' do
  pod 'data', :path => '../shared/core/data'
  pod 'datastore', :path => '../shared/core/datastore'
  pod 'model', :path => '../shared/core/model'
end